Repository trami25/Graph-Visualizer, pull requests merged in 2024-02, with the labels that each got.

#20 Feature/model tree
  .idea/Graph-Visualizer.iml
  .idea/misc.xml
  graph_visualizer_api/src/graph_visualizer_api/model/node.py
  graph_visualizer_api/src/graph_visualizer_api/model/tree.py
  graph_visualizer_api/tests/test_tree.py
  graph_visualizer_core/src/manage.py
Labels: feature

#24 HTML Data Source Plugin
  .idea/Graph-Visualizer.iml
  .idea/misc.xml
  graph_visualizer_api/src/graph_visualizer_api/model/edge.py
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/src/graph_visualizer_api/model/node.py
  graph_visualizer_api/tests/test_graph.py
  html_data_source_plugin/pyproject.toml
  html_data_source_plugin/src/html_data_source_plugin/__init__.py
  html_data_source_plugin/src/html_data_source_plugin/datasource.py
  html_data_source_plugin/src/html_data_source_plugin/main.py
  html_data_source_plugin/src/html_data_source_plugin/provider.py
Labels: feature

#27 Mermaid Syntax Diagrams
  README.md
Labels: documentation

#29 Plugin system
  graph_visualizer_platform/src/graph_visualizer_platform/exceptions.py
  graph_visualizer_platform/src/graph_visualizer_platform/plugins.py
  html_data_source_plugin/pyproject.toml
Labels: feature

#32 Block Visualizer Plugin
  block_visualizer_plugin/pyproject.toml
  block_visualizer_plugin/src/block_visualizer_plugin/__init__.py
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
Labels: feature

#47 Search and filter
  graph_visualizer_api/src/graph_visualizer_api/model/filter.py
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/tests/test_graph.py
Labels: feature

#46 fix: solved some rendering conflicts with json parsing of the Graph
  block_visualizer_plugin/src/block_visualizer_plugin/__init__.py
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  simple_visualizer_plugin/src/simple_visualizer_plugin/__init__.py
  simple_visualizer_plugin/src/simple_visualizer_plugin/simple_visualizer.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: bug

#35 Workspace system
  .idea/Graph-Visualizer.iml
  .idea/misc.xml
  README.md
  graph_visualizer_platform/src/graph_visualizer_platform/exceptions.py
  graph_visualizer_platform/src/graph_visualizer_platform/plugins.py
  graph_visualizer_platform/src/graph_visualizer_platform/singleton.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  graph_visualizer_platform/tests/test_workspaces.py
Labels: feature

#41 Update pyproject dependencies
  .github/workflows/tests.yml
  .gitignore
  block_visualizer_plugin/pyproject.toml
  simple_visualizer_plugin/pyproject.toml
Labels: bug

#48 Djagno set up
  .idea/Graph-Visualizer.iml
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  graph_visualizer_core/src/graph_visualizer_core/urls.py
  graph_visualizer_core/src/graphvisualizer/__init__.py
  graph_visualizer_core/src/graphvisualizer/admin.py
  graph_visualizer_core/src/graphvisualizer/apps.py
  graph_visualizer_core/src/graphvisualizer/migrations/__init__.py
  graph_visualizer_core/src/graphvisualizer/models.py
  graph_visualizer_core/src/graphvisualizer/templates/base.html
  graph_visualizer_core/src/graphvisualizer/tests.py
  graph_visualizer_core/src/graphvisualizer/urls.py
  graph_visualizer_core/src/graphvisualizer/views.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: feature

#52 Graph store
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/tests/test_graph.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
  graph_visualizer_platform/tests/test_store.py
Labels: feature

#51 Feature/issue 34/bird view
  .idea/Graph-Visualizer.iml
  .idea/misc.xml
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  graph_visualizer_api/tests/test_graph.py
  graph_visualizer_core/src/graphvisualizer/views.py
  html_data_source_plugin/src/html_data_source_plugin/provider.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: feature

#50 Feature/issue 49/connect platform and django
  .github/workflows/tests.yml
  .idea/Graph-Visualizer.iml
  graph_visualizer_core/src/graph_visualizer_core/settings.py
  graph_visualizer_core/src/graph_visualizer_core/urls.py
  graph_visualizer_core/src/graphvisualizer/apps.py
  graph_visualizer_core/src/graphvisualizer/templates/base.html
  graph_visualizer_core/src/graphvisualizer/urls.py
  graph_visualizer_core/src/graphvisualizer/views.py
  graph_visualizer_core/src/visualizer/__init__.py
  graph_visualizer_core/src/visualizer/admin.py
  graph_visualizer_core/src/visualizer/apps.py
  graph_visualizer_core/src/visualizer/migrations/__init__.py
  graph_visualizer_core/src/visualizer/models.py
  graph_visualizer_core/src/visualizer/templates/visualizer/base.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
  graph_visualizer_core/src/visualizer/tests.py
  graph_visualizer_core/src/visualizer/urls.py
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/pyproject.toml
  graph_visualizer_platform/src/graph_visualizer_platform/plugins.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  html_data_source_plugin/src/html_data_source_plugin/datasource.py
  html_data_source_plugin/src/html_data_source_plugin/provider.py
Labels: feature

#57 Data source configuration
  .gitignore
  .idea/Graph-Visualizer.iml
  graph_visualizer_api/src/graph_visualizer_api/datasource.py
  graph_visualizer_core/src/visualizer/templates/visualizer/config.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
  graph_visualizer_core/src/visualizer/urls.py
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  html_data_source_plugin/pyproject.toml
  html_data_source_plugin/src/html_data_source_plugin/configuration.py
  html_data_source_plugin/src/html_data_source_plugin/datasource.py
  json_data_source_plugin/data.json
  json_data_source_plugin/src/json_data_source_plugin/datasource.py
  json_data_source_plugin/src/json_data_source_plugin/json_data_source_plugin\data.json
  json_data_source_plugin/src/json_data_source_plugin/provider.py
Labels: feature

#59 Update graph model
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/tests/test_graph.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
Labels: enhancement

#60 Implemented tree view #issue-38
  graph_visualizer_api/pyproject.toml
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/src/graph_visualizer_api/model/tree.py
  graph_visualizer_api/tests/test_tree.py
  graph_visualizer_core/src/graph_visualizer_core/settings.py
  graph_visualizer_platform/src/graph_visualizer_platform/tempCodeRunnerFile.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view_data.json
  graph_visualizer_platform/src/visualization.html
  json_data_source_plugin/data.json
  json_data_source_plugin/src/json_data_source_plugin/main.py
  json_data_source_plugin/src/json_data_source_plugin/provider.py
  tree_view_data.yaml
Labels: feature

#61 #56 feat: add dynamically calculation of node size
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
Labels: enhancement

#65 Feature/issue 53/connection between views
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  graph_visualizer_core/src/visualizer/templates/visualizer/base.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/tempCodeRunnerFile.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  graph_visualizer_platform/src/visualization.html
  simple_visualizer_plugin/src/simple_visualizer_plugin/simple_visualizer.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: feature

#64 Plugin selection when creating a workspace
  graph_visualizer_core/src/visualizer/templates/visualizer/base.html
  graph_visualizer_core/src/visualizer/views.py
Labels: feature

#70 Path and template issues
  graph_visualizer_core/src/visualizer/templates/visualizer/visualization.html
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
Labels: fix

#71 Update workspace graphs on data source configuration change
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/plugins.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
Labels: fix

#74 Django filter layout
  graph_visualizer_api/src/graph_visualizer_api/model/filter.py
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/tests/test_graph.py
  graph_visualizer_core/src/visualizer/templates/visualizer/base.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
  graph_visualizer_core/src/visualizer/urls.py
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
Labels: feature

#72 Feature/issue 53/connection between views
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  graph_visualizer_core/src/visualizer/templates/visualizer/visualization.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view_data.json
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: enhancement

#62 Setup script
  .idea/Graph-Visualizer.iml
  graph_visualizer_platform/src/graph_visualizer_platform/plugins.py
  setup.py
Labels: feature

#76 Diagrams
  README.md
Labels: documentation

#80 Feature/issue 77/bird view update
  .idea/Graph-Visualizer.iml
  block_visualizer_plugin/src/block_visualizer_plugin/block_visualizer.py
  block_visualizer_plugin/src/template/block_visualizer_template.jinja2
  graph_visualizer_core/src/visualizer/views.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view_data.json
  graph_visualizer_platform/src/graph_visualizer_platform/workspaces.py
  simple_visualizer_plugin/src/simple_visualizer_plugin/simple_visualizer.py
  simple_visualizer_plugin/src/template/simple_visualizer_plugin/simple_visualizer_template.jinja2
Labels: enhancement

#81 Basic layout styles
  graph_visualizer_core/src/visualizer/templates/visualizer/base.html
  graph_visualizer_core/src/visualizer/templates/visualizer/config.html
  graph_visualizer_core/src/visualizer/templates/visualizer/workspace.html
Labels: feature

#82 Strategy filter pattern
  graph_visualizer_api/src/graph_visualizer_api/model/filter.py
  graph_visualizer_api/src/graph_visualizer_api/model/filter_strategies.py
  graph_visualizer_api/src/graph_visualizer_api/model/graph.py
  graph_visualizer_api/tests/test_graph.py
  graph_visualizer_platform/src/graph_visualizer_platform/store.py
Labels: feature

#73 Set directed for graphs in data sources
  html_data_source_plugin/src/html_data_source_plugin/datasource.py
  json_data_source_plugin/src/json_data_source_plugin/datasource.py
Labels: enhancement

#84 #83 exception for invalid data handled
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
Labels: bug, fix

#85 Hotfix/fix path
  graph_visualizer_api/src/graph_visualizer_api/model/tree.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view_data.json
Labels: fix

#86 Patch tree path
  graph_visualizer_api/src/graph_visualizer_api/model/tree.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view.py
  graph_visualizer_platform/src/graph_visualizer_platform/tree_view_data.json
Labels: fix
